-- Write your PostgreSQL query statement below
SELECT ROUND(SUM(CAST(tiv_2016 AS NUMERIC)), 2) AS tiv_2016 
FROM Insurance
WHERE CAST(tiv_2015 AS NUMERIC) IN  
(SELECT CAST(tiv_2015 AS NUMERIC)
FROM Insurance 
GROUP BY CAST(tiv_2015 AS NUMERIC) 
HAVING COUNT(*)>1 )
AND 
(CAST(lat AS DECIMAL), CAST(lon AS DECIMAL)) IN 
(SELECT CAST(lat AS DECIMAL), CAST(lon AS DECIMAL)
FROM Insurance 
GROUP BY  CAST(lat AS DECIMAL), CAST(lon AS DECIMAL)
HAVING COUNT(*)=1 )


